import { boolean, date, integer, jsonb, numeric, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })
export const investmentProducts = pgTable('investment_products', { id: serial('id').primaryKey(), name: text('name').notNull(), category: text('category').notNull(), fundSize: numeric('fundSize').notNull(), returnPa: numeric('returnPa').notNull(), risk: text('risk').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const userInvestments = pgTable('user_investments', { id: serial('id').primaryKey(), userId: text('userId').notNull(), productId: integer('productId').notNull(), amount: numeric('amount').notNull(), units: numeric('units').notNull().default('0'), status: text('status').notNull().default('active'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const insurancePolicies = pgTable('insurance_policies', { id: serial('id').primaryKey(), userId: text('userId').notNull(), policyNumber: text('policyNumber').notNull(), provider: text('provider').notNull(), type: text('type').notNull(), coverage: numeric('coverage').notNull(), premium: numeric('premium').notNull(), renewalDate: date('renewalDate').notNull(), status: text('status').notNull().default('active'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const auditLogs = pgTable('audit_logs', { id: serial('id').primaryKey(), userId: text('userId').notNull(), action: text('action').notNull(), entity: text('entity').notNull(), entityId: text('entityId'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('createdAt').notNull().defaultNow() })

export type InvestmentProduct = typeof investmentProducts.$inferSelect
export type InsurancePolicy = typeof insurancePolicies.$inferSelect
export type UserInvestment = typeof userInvestments.$inferSelect
